name: Publishing of new version

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Todo: release notes should go here
            - First Change
            - Second Change
          draft: false
          prerelease: false

  npm-publish:
    - uses: actions/checkout@v2

    - name: install
      run: yarn

    - name: publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: aa9a174b-030a-46df-819a-a86ca06e407b
