name: Publish to NPM

on:
  push:
    branches: [ ci/npm-publish ]

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: yarn
    
    - name: update package version
      run: yarn update-version

    - name: build
      run: yarn build

    - name: publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: aa9a174b-030a-46df-819a-a86ca06e407b
