name: Updates version and creates tag

on:
  push:
    branches: [ ci/npm-publish ]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v2
      
      # checks if the version in package.json is greater than the version in NPM
  
      - name: check package version
        id: checkVersion
        run: yarn check-version

      # if version was incorrect (lower or equal than NPM), update it and push changes

      - name: increment version if version was incorrect
        if: ${{ checkVersion.failure() }}
        run: yarn increment-version

      - name: commit changes if version was incorrect
        if: ${{ checkVersion.failure() }}
        run: echo "todo commit"

      - name: push commit if version was incorrect
        if: ${{ checkVersion.failure() }}
        run: echo "todo push"

      # otherwise, create new tag with the last commit in master

      - name: create tag if version was correct
        if: ${{ checkVersion.success() }}
        run: echo "todo push"

