name: Update version and create tag

on:
  push:
    branches: [ ci/npm-publish ]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v2
      
      # checks if the version in package.json is greater than the version in NPM
  
      - name: check package version
        id: check
        continue-on-error: true
        run: yarn check-version

      # if version was incorrect (lower or equal than NPM), update it and push changes

      - name: increment version
        id: increment
        if: ${{ steps.check.outcome == 'failure' }}
        run: yarn increment-version

      - name: store version in variable
        id: getVersion
        if: ${{ steps.increment.outcome == 'success' }}
        run: echo "##[set-output name=value;]$(yarn get-version)"

      - name: create pull request
        if: ${{ steps.getVersion.outcome == 'success' }}
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: updates package version to ${{ steps.getVersion.output.version }}
          title: Updates package version to ${{ steps.getVersion.output.version }}
          body: updates package version to ${{ steps.getVersion.output.version }}
          branch: patch/increment-version-${{ steps.getVersion.output.version }}

      # - name: create new branch
      #   id: branch
      #   if: ${{ steps.check.outcome == 'failure' }}
      #   run: git checkout -b fix/increment-version-$GITHUB_RUN_NUMBER

      # - name: increment version
      #   id: increment
      #   if: ${{ steps.branch.outcome == 'success' }}
      #   run: yarn increment-version

      # - name: commit changes
      #   id: commit
      #   if: ${{ steps.increment.outcome == 'success' }}
      #   run: git add -A && git commit -m "Incrementing version" --author=$GITHUB_ACTOR

      # - name: push commit
      #   if: ${{ steps.commit.outcome == 'success' }}
      #   run: git push origin fix/increment-version-$GITHUB_RUN_NUMBER

      # otherwise, create new tag with the last commit in master

      - name: create tag if version was correct
        if: ${{ steps.check.outcome == 'success' }}
        run: echo "todo push"

